# Generated by Django 5.0.3 on 2024-03-27 14:17

import django.core.validators
import django.db.models.deletion
import veggie_recipe_book.recipes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingredient Name', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Ingredient name cannot be fewer than 2 letters long')])),
                ('measurement_unit', models.CharField(choices=[('cups', 'Cups'), ('tbs', 'Tablespoons'), ('ts', 'Teaspoons'), ('pinch', 'Pinch'), ('ml', 'Milliliters'), ('l', 'Liters'), ('g', 'Grams'), ('kg', 'Kilograms')], help_text='Measurement Unit', max_length=5)),
                ('additional_context', models.CharField(blank=True, help_text='Chopped, At room temperature, Melted, Etc', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Recipe Name', max_length=75, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Title cannot be fewer than 2 letters long')])),
                ('recipe_type', models.CharField(choices=[('BG', 'Baked Goods'), ('DS', 'Desserts'), ('SD', 'Sides'), ('MN', 'Mains'), ('DR', 'Drinks')], help_text='Recipe Type', max_length=2)),
                ('picture', models.ImageField(blank=True, help_text='Upload a picture', null=True, upload_to='recipe_pictures/', validators=[veggie_recipe_book.recipes.validators.validate_image_size])),
                ('description', models.TextField(help_text='Your Recipe')),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Your comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
