# Generated by Django 5.0.3 on 2024-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('cups', 'Cups'), ('tbs', 'Tablespoons'), ('ts', 'Teaspoons'), ('pinch', 'Pinch'), ('ml', 'Millilitres'), ('l', 'Litres'), ('g', 'Grams'), ('kg', 'Kilograms'), ('-', '--')], help_text='Measurement Unit', max_length=5),
        ),
    ]
