# Generated by Django 5.0.3 on 2024-03-27 14:17

import django.core.validators
import django.db.models.deletion
import veggie_recipe_book.profiles.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(help_text='Your Username', max_length=35, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Username cannot be fewer than 2 letters long'), veggie_recipe_book.profiles.validators.UsernameValidator()])),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2, message='First name cannot be fewer than 2 letters long')])),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1, message='Last name cannot be fewer than 1 letters long')])),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
