# Generated by Django 5.0.3 on 2024-03-28 14:55

import veggie_recipe_book.recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a picture', null=True, upload_to='profile_pictures/', validators=[veggie_recipe_book.recipes.validators.validate_image_size]),
        ),
    ]
