# Generated by Django 5.0.3 on 2024-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_profile_pic_alter_profile_username'),
        ('recipes', '0006_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(to='recipes.recipe'),
        ),
    ]
